# Generated by Django 5.0.6 on 2024-06-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
